### ISSUE TITLE
I crafted red dye with flower and disabled ROSE_RED, RED_DYE and DYE. Instead of working they gave me this error.

### ISSUE THREAD

**Issue by kyzzf** [mattisadev/DisableCrafting#1] opened 2021-01-30 20:14 UTC
Could not pass event CraftItemEvent to DisableCrafting v1.0.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[Skyblock.jar:git-Paper-1244]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Skyblock.jar:git-Paper-1244]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Skyblock.jar:git-Paper-1244]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[Skyblock.jar:git-Paper-1244]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[Skyblock.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1975) ~[Skyblock.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[Skyblock.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[Skyblock.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Skyblock.jar:git-Paper-1244]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_271]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_271]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Skyblock.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [Skyblock.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [Skyblock.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [Skyblock.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [Skyblock.jar:git-Paper-1244]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.IllegalArgumentException: No enum constant com.mww.disablecrafting.utils.assistors.XMaterial.crafting_table
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_271]
        at com.mww.disablecrafting.utils.assistors.XMaterial.valueOf(XMaterial.java:46) ~[?:?]
        at com.mww.disablecrafting.listeners.CraftListener.craftItem(CraftListener.java:31) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor105.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[Skyblock.jar:git-Paper-1244]
        ... 16 more

**Comment by matthew-wiggins** [comment] 2021-01-31 06:19
Could you please provide me with the following information:

> - Version of Disable Crafting
> - Version of Server
> - Pastebin of your config.yml file

Thank you,
Matthew W

**Comment by kyzzf** [comment] 2021-01-31 17:00
- Version of Disable Crafting: 1.0.4
   - Version of Server: paper-1.12.2-1618
   - Pastebin of your config.yml file:

#Here is where you will specify what items you want to disable the crafting
of.
# !!! item IDs or data tags are not allowed, only material names (Use 1.16
material list if needing to use data tags) !!!

items:
  spawn:
    - BRICKS
    - CLAY
    - WHITE_TERRACOTTA
    - ORANGE_TERRACOTTA
    - MAGENTA_TERRACOTTA
    - LIGHT_BLUE_TERRACOTTA
    - YELLOW_TERRACOTTA
    - LIME_TERRACOTTA
    - PINK_TERRACOTTA
    - GRAY_TERRACOTTA
    - LIGHT_GRAY_TERRACOTTA
    - CYAN_TERRACOTTA
    - PURPLE_TERRACOTTA
    - BLUE_TERRACOTTA
    - BROWN_TERRACOTTA
    - GREEN_TERRACOTTA
    - RED_TERRACOTTA
    - BLACK_TERRACOTTA
    - TERRACOTTA
    - CLAY_BALL
    - crafting_table
    - jukebox
    - brick
    - ROSE_RED
    - CACTUS_GREEN
    - PURPLE_DYE
    - CYAN_DYE
    - LIGHT_GRAY_DYE
    - GRAY_DYE
    - PINK_DYE
    - LIME_DYE
    - DANDELION_YELLOW
    - LIGHT_BLUE_DYE
    - MAGENTA_DYE
    - ORANGE_DYE
    - RED_DYE
    - GREEN_DYE
    - YELLOW_DYE
    - BLUE_DYE
    - BROWN_DYE
    - BLACK_DYE
    - WHITE_DYE
    - DYE

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfritt.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by matthew-wiggins** [comment] 2021-02-02 17:27
Try making these items all capitalized

>     - crafting_table
>     - jukebox
>     - brick

**Comment by matthew-wiggins** [comment] 2021-02-02 17:29
If this fixes your issue, I will force all items to be read as capitalized names. Your error shows there is an issue finding an item for 'crafting_table' 

Caused by: java.lang.IllegalArgumentException: **No enum constant** com.mww.disablecrafting.utils.assistors.XMaterial.**crafting_table**

**Comment by kyzzf** [comment] 2021-02-02 17:59
Didn't fix my issue. Those 3 already works, even if I change them it doesn't let the red dye or the other dyes work.

**Comment by matthew-wiggins** [comment] 2021-02-02 19:33
Check the most recent update for the fix to your issues. (Version 1.0.5)

**Comment by kyzzf** [comment] 2021-02-02 19:56
Thanks, I'll check it out.

Den tis 2 feb. 2021 20:33Matthew W. <notifications@github.com> skrev:

**Comment by kyzzf** [comment] 2021-02-03 18:35
It works now, but it spams your chat with over 10 messages of that you can't craft this.

**Comment by matthew-wiggins** [comment] 2021-02-03 20:44
> It works now, but it spams your chat with over 10 messages of that you can't craft this.

Can you please send me your console logs (if there are any errors).

**Comment by kyzzf** [comment] 2021-02-03 21:00
There is no error this time.

**Comment by matthew-wiggins** [comment] 2021-02-03 21:14
> There is no error this time.

I am not able to replicate the issue you're encountering on my end. I am running version 1.0.5 of DisableCrafting, with your config, on my paper-1.12.2 server. Could you maybe get a video of the issue so I can see what happening?

**Comment by kyzzf** [comment] 2021-03-02 09:06
sorry for late response, https://youtu.be/BYBGtPFLmp4

**Comment by mattisadev** [comment] 2021-03-03 04:22
> sorry for late response, https://youtu.be/BYBGtPFLmp4

Can you please join the support [Discord](http://discord.io/mattdev)?

Mention me in the correct support channel so we can continue talking there.

**Comment by mattisadev** [comment] 2021-03-06 22:12
Issue fixed in [version 1.0.7](https://www.spigotmc.org/resources/%E2%9D%8E-1-8-1-16-disable-crafting-%E2%9D%8E-a-way-to-disable-the-crafting-of-any-item.85786/update?update=391138)

**Closed by mattisadev** 2021-03-06 22:12 UTC
Labels: BUG, SOLVED
